FROM nginx:alpine

COPY config/nginx.conf /etc/nginx/nginx.conf
COPY widget.html /usr/share/nginx/html/widget.html
COPY embed.html /usr/share/nginx/html/embed.html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
